/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.robertpyke.ohmage;

public final class R {
    public static final class array {
        public static final int E12=0x7f050003;
        public static final int E192=0x7f050007;
        public static final int E24=0x7f050004;
        public static final int E48=0x7f050005;
        public static final int E6=0x7f050002;
        public static final int E96=0x7f050006;
        public static final int tolerance_array=0x7f050001;
        public static final int unit_array=0x7f050000;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int b1_top_padding=0x7f060012;
        public static final int b2_top_padding=0x7f060013;
        public static final int b3_top_padding=0x7f060014;
        public static final int b4_top_padding=0x7f060015;
        public static final int b_height=0x7f060008;
        public static final int co_b1_width=0x7f060000;
        public static final int co_b2_width=0x7f060001;
        public static final int co_b3_width=0x7f060002;
        public static final int co_b4_width=0x7f060003;
        public static final int co_b_text_size=0x7f06000b;
        public static final int co_selector_l_padding=0x7f06000f;
        public static final int co_text_size=0x7f060009;
        public static final int lc_rc_padding=0x7f06000d;
        public static final int middle_b_lr_margin=0x7f060011;
        public static final int oc_b1_width=0x7f060004;
        public static final int oc_b2_width=0x7f060005;
        public static final int oc_b3_width=0x7f060006;
        public static final int oc_b4_width=0x7f060007;
        public static final int oc_b_text_size=0x7f06000c;
        public static final int oc_text_size=0x7f06000a;
        public static final int plus_minus_left_padding=0x7f060016;
        public static final int text_padding=0x7f060010;
        public static final int top_padding=0x7f06000e;
        public static final int update_button_left_padding=0x7f060017;
    }
    public static final class drawable {
        public static final int black=0x7f020002;
        public static final int blue=0x7f020008;
        public static final int brown=0x7f020003;
        public static final int gold=0x7f02000c;
        public static final int gray=0x7f02000a;
        public static final int green=0x7f020007;
        public static final int icon=0x7f020000;
        public static final int orange=0x7f020005;
        public static final int red=0x7f020004;
        public static final int resistor_background_5=0x7f020001;
        public static final int silver=0x7f02000d;
        public static final int violet=0x7f020009;
        public static final int white=0x7f02000b;
        public static final int yellow=0x7f020006;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f07001b;
        public static final int ScrollView01=0x7f07000f;
        public static final int TableLayout02=0x7f07000a;
        public static final int TableRow01=0x7f07000b;
        public static final int TableRow02=0x7f070002;
        public static final int TableRow03=0x7f070004;
        public static final int TableRow04=0x7f070006;
        public static final int TableRow06=0x7f070008;
        public static final int band1=0x7f070003;
        public static final int band2=0x7f070005;
        public static final int band3=0x7f070007;
        public static final int band4=0x7f070009;
        public static final int coColorToOhmTabOuterLinearLayout=0x7f070000;
        public static final int coOhmValue=0x7f07000c;
        public static final int coResistorImageTableLayout=0x7f070001;
        public static final int eStdList=0x7f07000e;
        public static final int e_list_position_t_v=0x7f07000d;
        public static final int errorText=0x7f070010;
        public static final int infoText=0x7f070011;
        public static final int ocBand1TextView=0x7f070013;
        public static final int ocBand2TextView=0x7f070014;
        public static final int ocBand3TextView=0x7f070015;
        public static final int ocBand4TextView=0x7f070016;
        public static final int ocOhmToColorTabOuterLinearLayout=0x7f070012;
        public static final int ocOhmValueAutoCompleteTextView=0x7f070017;
        public static final int ocPlusOrMinusText=0x7f070019;
        public static final int ocToleranceSpinner=0x7f07001a;
        public static final int ocUnitSpinner=0x7f070018;
        public static final int updateButton=0x7f07001c;
    }
    public static final class layout {
        public static final int color_to_ohm_tab=0x7f030000;
        public static final int e_list_position=0x7f030001;
        public static final int e_standard_tab=0x7f030002;
        public static final int error_output=0x7f030003;
        public static final int info_output=0x7f030004;
        public static final int ohm_to_color_tab=0x7f030005;
    }
    public static final class string {
        public static final int E12_Tolerance=0x7f04001e;
        public static final int E192_Tolerance=0x7f040022;
        public static final int E24_Tolerance=0x7f04001f;
        public static final int E48_Tolerance=0x7f040020;
        public static final int E6_Tolerance=0x7f04001d;
        public static final int E96_Tolerance=0x7f040021;
        public static final int app_description=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int band1_prompt=0x7f040009;
        public static final int band2_prompt=0x7f04000a;
        public static final int band3_prompt=0x7f04000b;
        public static final int band4_prompt=0x7f04000c;
        public static final int co_instructions=0x7f040006;
        public static final int color_to_ohm_label=0x7f04000d;
        public static final int e_std_label=0x7f04000f;
        public static final int email=0x7f040004;
        public static final int future_additions=0x7f040008;
        public static final int home_page=0x7f040003;
        public static final int kilaOhm=0x7f040012;
        public static final int megaOhm=0x7f040013;
        public static final int miliOhm=0x7f040010;
        public static final int oc_instructions=0x7f040007;
        public static final int ohm=0x7f040011;
        public static final int ohm_value_to_color_label=0x7f04000e;
        public static final int plus_or_minus_symbol=0x7f040014;
        public static final int support_message=0x7f040005;
        public static final int tol_0p05pc=0x7f040015;
        public static final int tol_0p1pc=0x7f040016;
        public static final int tol_0p25pc=0x7f040017;
        public static final int tol_0p5pc=0x7f040018;
        public static final int tol_10pc=0x7f04001c;
        public static final int tol_1pc=0x7f040019;
        public static final int tol_2pc=0x7f04001a;
        public static final int tol_5pc=0x7f04001b;
        public static final int version=0x7f040002;
    }
}
